### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by grantcarthew** [majorleaguesoccer/stacklog#3]
Hi.
I'm still a user of stacklog however I may be the only one.
Can you add me as a maintainer both here and on the NPM package please?

I know what I am doing and as a form or resume: https://www.npmjs.com/package/rethinkdb-job-queue

@sorensen, @smerrill, @jslatts, @baznar, @kkemple 

Sorry for the spam. I don't know who is still in charge here.

I would rather be a maintainer here than fork it and publish my own.

**Comment by jslatts** [comment]
@grantcarthew I don't work at MLS and I don't have access this repo, but I forked it when you sent the PR a few years ago (https://github.com/jslatts/stacklog) and pushed that version to NPM, so I would call that the "official" repo now. I just added you as a maintainer there, so go for it.

And I'm stoked that you are still using it!

**Comment by grantcarthew** [comment]
Oh, you're right @jslatts. I had forgotten that. My application was crashing yesterday and it was due to logging. I suspect it is Winston now.

Thanks mate.
